### ISSUE TITLE
message = FALSE / warning = FALSE chunk parameters are not respected for remote blocks

### ISSUE THREAD

**Issue by margaret-colville** [databrickslabs/brickster#58]
If I have a command that returns messages / warnings (eg loading `dplyr`, since it has function conflict names with base R), the `message=FALSE` and `warning=FALSE` settings are not respected and I would have to silence each one individually.
[message-FALSE.zip](https://github.com/user-attachments/files/16326908/message-FALSE.zip)

**Comment by zacdav-db** [comment]
This requires altering the user code being sent to Databricks.

Because the code is treated as literal text and sent to an API that executes the code the code is evaluated external to the existing R session and would need to be wrapped in `supressMessages()` and `supressWarnings()`.

Similar to https://github.com/databrickslabs/brickster/issues/60 I'm inclined to consider not adding this and favour adding better features to connect and run code against Databricks. knitr engines and their options is an extreme list of things to support.

**Comment by zacdav-db** [comment]
Removing `knitr` engine from package in next version.
