### ISSUE TITLE
fig.height and fig.width parameters are not respected for remote blocks

### ISSUE THREAD

**Issue by margaret-colville** [databrickslabs/brickster#60]
If I set the `fig.height` and `fig.width` parameters for a remote code block in an rmd, the image instead is returned at the same default size as always.
[fig-height-fig-width.zip](https://github.com/user-attachments/files/16326937/fig-height-fig-width.zip)

**Comment by zacdav-db** [comment]
I've been investigating ways to adjust this but its quite complex due to the nature of the integration.

For context, the knitr engine routes code to be executed on the specified Databricks cluster, when it does this the code is executed via slightly different mechanisms for each language. For R, it controls the size of the viz via options that would need to be adjusted and changed back for every command execution. Not only does it require it to be changed, the option doesn't apply to the command where its changed.

Long story short, supporting this currently would duplicate the number of commands sent to the cluster and add significant overhead.

My intention when building this feature was predominantly a "**hack**" for interactive use outside Databricks notebooks and not for it to be the vehicle to render reports as most traditionally use rmarkdown for.

I intended to either:
1. Revisit this once the Databricks capability supports adjusting the image size options without requiring a second command
2. Consider removing the knitr engine in order to add other features that integrate better

I'm currently leaning towards (2) as it will remove confusion and provide a more opinionated approach.

**Comment by zacdav-db** [comment]
Removing `knitr` engine from package in next version.
